- hosts: k8s_master:k8s_nodes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Configure Docker to use systemd cgroup
      copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"]
          }
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
    - name: Start Docker
      service:
        name: docker
        state: restarted
        enabled: yes
    - name: Remove old Kubernetes repo
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent
    - name: Remove old Kubernetes key
      file:
        path: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        state: absent
    - name: Add Kubernetes apt key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        state: present
    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        state: present
        filename: kubernetes
        update_cache: yes
    - name: Install kubeadm, kubelet, kubectl
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectlt
