- hosts: monitoring
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
